In [1]:
import numpy as np

In [8]:
#Question 1
arr = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
print(arr) #Print the array
print(arr.ndim) #Number of dimensions
print(arr.shape) #Shape of array
print(arr.size) #Size of array

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2
(5, 2)
10


In [9]:
#Question 2
arr2 = np.arange(start=200, stop=300, step=10).reshape(5,2)
print(arr2)

[[200 210]
 [220 230]
 [240 250]
 [260 270]
 [280 290]]


In [12]:
#Question 3
arr3 = np.arange(start=1,stop=10, step=1).reshape(3,3)
print(arr3[2]) #Printing 3rd row of the matrix

[7 8 9]


In [29]:
#Question 4
arr1 = np.arange(start=1,stop=100, step=5).reshape(5,4)
print(arr1, "\n")
arr2 = arr1[1:5:2]
arr3 = arr1[0:5:2]
print(arr2, "\n") #Even rows
print(arr3) #Odd rows

[[ 1  6 11 16]
 [21 26 31 36]
 [41 46 51 56]
 [61 66 71 76]
 [81 86 91 96]] 

[[21 26 31 36]
 [61 66 71 76]] 

[[ 1  6 11 16]
 [41 46 51 56]
 [81 86 91 96]]


In [37]:
#Question 5
arr = np.random.randint(5, size = (8,3))
print(arr, "\n") #Printing the arrays
arr2 = np.array_split(arr, 4)
for i in range(0,4):
    print(arr2[i], "\n")  #Printing the spliting arrays

[[1 0 2]
 [0 2 0]
 [3 3 0]
 [2 1 2]
 [0 4 1]
 [1 0 2]
 [3 3 0]
 [0 0 0]] 

[[1 0 2]
 [0 2 0]] 

[[3 3 0]
 [2 1 2]] 

[[0 4 1]
 [1 0 2]] 

[[3 3 0]
 [0 0 0]] 



In [44]:
#Question 6
arr = np.random.randint(100, size=(4,4))
print(arr, "\n")
arr = arr[:, arr[2,:].argsort()]
print(arr, "\n") 
arr = arr[arr[:, 3].argsort()] #Sort according to column
print(arr)

[[23 50  9 49]
 [33 11 27 37]
 [97 86 81 44]
 [51 38 10  6]] 

[[49  9 50 23]
 [37 27 11 33]
 [44 81 86 97]
 [ 6 10 38 51]] 

[[49  9 50 23]
 [37 27 11 33]
 [ 6 10 38 51]
 [44 81 86 97]]


In [49]:
#Question 7
arr = np.random.randint(100, size=(3,3))
print(arr, "\n") #Original array
arr2 = np.random.randint(100, size=(3))
arr[:,2] = arr2
print(arr)

[[ 8 90 56]
 [34 10 73]
 [79 29 13]] 

[[ 8 90 28]
 [34 10 77]
 [79 29 43]]
